defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[retry]
[api]
[ping]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "${SERVER_HOST}"
watch = true
exposedByDefault = false
