version: '3.6'

networks:
    hs_net:
        driver: bridge
        name: hs_net
        ipam:
            driver: default
    default:
        external:
          name: hs_net

volumes:
    portainer_data:
        driver: local
        name: portainer_data

services:
    traefik:
        container_name: traefik
        restart: on-failure
        image: traefik
        command: --api --docker
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './traefik.toml:/traefik.toml'
        labels:
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefixStrip: /traefik"
            - "traefik.port=8080"
        networks:
            - hs_net

    portainer:
        container_name: portainer
        restart: unless-stopped
        volumes:
            - 'portainer_data:/data'
        ports:
           - '9000:9000'
        labels:
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=9000"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefixStrip: /portainer"
        image: portainer/portainer
        networks:
            - hs_net
