defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
[retry]
[api]
[ping]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "${SERVER_HOST}"
watch = true
exposedByDefault = false
