version: '3.6'

networks:
    hs_net:
        driver: bridge
        name: hs_net
        ipam:
            driver: default
    default:
        external:
          name: hs_net

volumes:
    portainer_data:
        driver: local
        name: portainer_data
    nginx_data:
        driver: local
        name: nginx_data

services:
# traefik simple reverse proxy
    traefik:
        container_name: traefik:latest
        restart: on-failure
        image: traefik
        command: traefik --api --docker --acme=true --acme.domains=''${SERVER_HOST}' --acme.email='${EMAIL_ADDR}' --acme.entrypoint=https --acme.storage=acme.json --acme.caServer='https://acme-staging-v02.api.letsencrypt.org/directory'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './traefik/traefik.toml:/traefik.toml'
        labels:
            - "traefik.backend=traefik"
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefixStrip: /traefik"
            - "traefik.frontend.auth.basic.users=./traefik/.htpasswd"
            - "traefik.port=8080"
        networks:
            - hs_net

# nginx for simple landing page
    nginx:
        image: linuxserver/nginx
        container_name: nginx
        restart: always
        depends_on:
          - traefik
        volumes:
            - '${DOCKER_DATA_DIR}/nginx/config:/config'
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=Europe/Dublin
        labels:
            - "traefik.backend=nginx"
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${SERVER_HOST}"
            - "traefik.port=80"

# portainer for docker management GUI
    portainer:
        container_name: portainer
        restart: unless-stopped
        depends_on:
          - traefik
        volumes:
            - 'portainer_data:/data'
        labels:
            - "traefik.backend=portainer"
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=9000"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefixStrip: /portainer"
            - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
            - "traefik.frontend.redirect.replacement=$$1/portainer/"
            - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
        image: portainer/portainer

# Sonarr downloader
    sonarr:
        container_name: sonarr
        restart: unless-stopped
        depends_on:
          - traefik
        volumes:
            - '${DOCKER_DATA_DIR}/sonarr:/config'
# add more mounts as required: EG tv
#            - '/mnt/tv:/media/tv'
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=Europe/Dublin
        image: linuxserver/sonarr
        labels:
            - "traefik.backend=sonarr"
            - "traefik.docker.network=hs_net"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefix:/sonarr"
            - "traefik.port=8989"
# Needed to allow this to manually set path in sonarr. Disable after completed
#        ports:
#            - '8989:8989'


# Radarr
    radarr:
        container_name: radarr
        restart: unless-stopped
        depends_on:
          - traefik
        volumes:
            - '${DOCKER_DATA_DIR}/radarr:/config'
# add more mounts as required: EG movies
#            - '/mnt/nfs/movies:/media/movies'
        image: linuxserver/radarr
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=Europe/Dublin
        labels:
            - "traefik.enable=true"
            - "traefik.backend=radarr"
            - "traefik.docker.network=hs_net"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefix: /radarr"
            - "traefik.port=7878"
# Needed to allow this to manually set path in Radarr. Disable after completed
#        ports:
#            - '7878:7878'


# Sabnzbd
    sabnzbd:
        container_name: sabnzbd
        image: linuxserver/sabnzdb
        restart: unless-stopped
        depends_on:
          - traefik
        volumes:
            - '${DOCKER_DATA_DIR}/sabnzbd:/config'
            - '${DOWNLOADS_DIR}/sabnzbd/completed:/complete'
            - '${DOWNLOADS_DIR}/sabnzbd/incomplete:/incomplete'
            - '${DOWNLOADS_DIR}/sabnzbd/watch:/watch'
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=Europe/Dublin
        labels:
            - "traefik.enable=true"
            - "traefik.backend=sabnzbd
            - "traefik.docker.network=hs_net"
            - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefix: /sabnzbd"
